In [1]:
import numpy as np

In [2]:
np.array( ((11,12,13), (21,22,23), (31,32,33)) )

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [3]:
x = np.array(((11,12,13), (21,22,23), (31,32,33)))
x.ndim

2

In [4]:
ax = np.array([1,2,3])
ay = np.array([3,4,5])

In [22]:
print(ax)
print(ax * 2)
print(ax+10)
print(np.sqrt(ax))
print(np.cos(ax))
print(ax-ay)
print(np.where(ax<2, ax ,10))
print('----------------------')
m = np.matrix([ax,ay, ax])
print(m)
print(m.T)

[1 2 3]
[2 4 6]
[11 12 13]
[1.         1.41421356 1.73205081]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2 -2 -2]
[ 1 10 10]
----------------------
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]


In [23]:
grid1 = np.zeros(shape=(5,5), dtype=float)
grid2 = np.ones(shape=(5,5), dtype=float)
print(grid1)
print(grid2)
print(grid1+10)
print(grid2[:,2]*2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]
[2. 2. 2. 2. 2.]
